version: '3.8'

services:
  gui:
    build:
      context: ./gui
    container_name: gui
    hostname: gui
    networks:
      aeropuerto_net:
        ipv4_address: 192.168.100.100
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    stdin_open: true

  nodo1:
    build:
      context: ./nodo1
    container_name: nodo1
    hostname: nodo1
    volumes:
      - ./ssh:/home/mpiuser/.ssh:ro
    networks:
      aeropuerto_net:
        ipv4_address: 192.168.100.11
    tty: true
    stdin_open: true
    environment:
    - GUI_HOST=192.168.100.100
    ports:
      - "2201:22"  

  nodo2:
    build:
      context: ./nodo2
    container_name: nodo2
    hostname: nodo2
    volumes:
      - ./ssh:/home/mpiuser/.ssh:ro
    networks:
      aeropuerto_net:
        ipv4_address: 192.168.100.12
    tty: true
    stdin_open: true
    environment:
    - GUI_HOST=192.168.100.100
    ports:
      - "2202:22"

  nodo3:
    build:
      context: ./nodo3
    container_name: nodo3
    hostname: nodo3
    volumes:
      - ./ssh:/home/mpiuser/.ssh:ro
    networks:
      aeropuerto_net:
        ipv4_address: 192.168.100.13
    tty: true
    stdin_open: true
    environment:
    - GUI_HOST=192.168.100.100
    ports:
      - "2203:22"

networks:
  aeropuerto_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24